/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 2.6.12.5
 * Sun Dec 26 23:23:15 2021
 */
#define AUTOCONF_INCLUDED
#define CONFIG_ARM 1
#define CONFIG_MMU 1
#define CONFIG_UID16 1
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#define CONFIG_GENERIC_CALIBRATE_DELAY 1
#define CONFIG_GENERIC_IOMAP 1

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_CLEAN_COMPILE 1
#define CONFIG_BROKEN_ON_SMP 1
#define CONFIG_INIT_ENV_ARG_LIMIT 32

/*
 * General setup
 */
#define CONFIG_LOCALVERSION ""
#undef CONFIG_SWAP
#define CONFIG_SYSVIPC 1
#define CONFIG_POSIX_MQUEUE 1
#undef CONFIG_BSD_PROCESS_ACCT
#define CONFIG_SYSCTL 1
#undef CONFIG_AUDIT
#define CONFIG_HOTPLUG 1
#define CONFIG_KOBJECT_UEVENT 1
#define CONFIG_IKCONFIG 1
#define CONFIG_IKCONFIG_PROC 1
#define CONFIG_EMBEDDED 1
#define CONFIG_KALLSYMS 1
#undef CONFIG_KALLSYMS_EXTRA_PASS
#define CONFIG_PRINTK 1
#define CONFIG_BUG 1
#define CONFIG_BASE_FULL 1
#define CONFIG_FUTEX 1
#define CONFIG_EPOLL 1
#define CONFIG_CC_OPTIMIZE_FOR_SIZE 1
#define CONFIG_SHMEM 1
#define CONFIG_CC_ALIGN_FUNCTIONS 0
#define CONFIG_CC_ALIGN_LABELS 0
#define CONFIG_CC_ALIGN_LOOPS 0
#define CONFIG_CC_ALIGN_JUMPS 0
#undef CONFIG_TINY_SHMEM
#define CONFIG_BASE_SMALL 0

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#undef CONFIG_MODULE_FORCE_UNLOAD
#define CONFIG_OBSOLETE_MODPARM 1
#undef CONFIG_MODVERSIONS
#undef CONFIG_MODULE_SRCVERSION_ALL
#undef CONFIG_KMOD

/*
 * System Type
 */
#undef CONFIG_ARCH_CLPS7500
#undef CONFIG_ARCH_CLPS711X
#undef CONFIG_ARCH_CO285
#undef CONFIG_ARCH_EBSA110
#undef CONFIG_ARCH_CAMELOT
#undef CONFIG_ARCH_FOOTBRIDGE
#undef CONFIG_ARCH_INTEGRATOR
#undef CONFIG_ARCH_IOP3XX
#undef CONFIG_ARCH_IXP4XX
#undef CONFIG_ARCH_IXP2000
#undef CONFIG_ARCH_L7200
#undef CONFIG_ARCH_PXA
#undef CONFIG_ARCH_RPC
#undef CONFIG_ARCH_SA1100
#undef CONFIG_ARCH_S3C2410
#undef CONFIG_ARCH_SHARK
#undef CONFIG_ARCH_LH7A40X
#undef CONFIG_ARCH_OMAP
#undef CONFIG_ARCH_VERSATILE
#define CONFIG_ARCH_CELESTIAL_ORION 1
#undef CONFIG_ARCH_IMX
#undef CONFIG_ARCH_H720X
#undef CONFIG_ARCH_ORION_CSM1100
#undef CONFIG_ARCH_ORION_CSM1200
#define CONFIG_ARCH_ORION_CSM1201 1
#undef CONFIG_ARCH_ORION_CSM1201_J
#define CONFIG_AVRES_ALLOC_SUPPORT 1
#define CONFIG_BASE_DDR_ADDR 0x10000000
#define CONFIG_FB0_SIZE 0xc00000
#define CONFIG_FB0_REGION "(BASE_DDR_ADDR - FB0_SIZE)"
#define CONFIG_FB1_SIZE 0xc00000
#define CONFIG_FB1_REGION "(FB0_REGION - FB1_SIZE)"
#define CONFIG_FB2_SIZE 0x400000
#define CONFIG_FB2_REGION "(FB0_REGION + FB0_SIZE - FB2_SIZE)"
#define CONFIG_FB3_SIZE 0x400000
#define CONFIG_FB3_REGION "(FB1_REGION + FB1_SIZE - FB3_SIZE)"
#define CONFIG_ETHERNET_SIZE 0x100000
#define CONFIG_ETHERNET_REGION "(FB1_REGION - ETHERNET_SIZE)"
#define CONFIG_XPORT_SIZE 0x600000
#define CONFIG_XPORT_REGION "(ETHERNET_REGION - XPORT_SIZE)"
#define CONFIG_AUD_SIZE 0x100000
#define CONFIG_AUD_REGION "(XPORT_REGION - AUD_SIZE)"
#define CONFIG_DPB0_SIZE 0x2500000
#define CONFIG_DPB0_REGION "(AUD_REGION - DPB0_SIZE)"
#define CONFIG_CPB0_SIZE 0x900000
#define CONFIG_CPB0_REGION "(DPB0_REGION - CPB0_SIZE)"
#define CONFIG_CPB0_DIR_SIZE 0x9000
#define CONFIG_CPB0_DIR_REGION "(CPB0_REGION - CPB0_DIR_SIZE)"

/*
 * Processor Type
 */
#define CONFIG_CPU_32 1
#define CONFIG_CPU_ARM926T 1
#define CONFIG_CPU_32v5 1
#define CONFIG_CPU_ABRT_EV5TJ 1
#define CONFIG_CPU_CACHE_VIVT 1
#define CONFIG_CPU_COPY_V4WB 1
#define CONFIG_CPU_TLB_V4WBI 1

/*
 * Processor Features
 */
#define CONFIG_ARM_THUMB 1
#undef CONFIG_CPU_ICACHE_DISABLE
#undef CONFIG_CPU_DCACHE_DISABLE
#undef CONFIG_CPU_DCACHE_WRITETHROUGH
#undef CONFIG_CPU_CACHE_ROUND_ROBIN

/*
 * Bus support
 */
#define CONFIG_ISA_DMA_API 1

/*
 * PCCARD (PCMCIA/CardBus) support
 */
#define CONFIG_PCCARD 1
#undef CONFIG_PCMCIA_DEBUG
#define CONFIG_PCMCIA 1

/*
 * PC-card bridges
 */
#define CONFIG_PCMCIA_ORION 1
#define CONFIG_PCMCIA_ORION_CI 1
#undef CONFIG_TCIC

/*
 * Kernel Features
 */
#undef CONFIG_SMP
#undef CONFIG_PREEMPT
#undef CONFIG_DISCONTIGMEM
#define CONFIG_ALIGNMENT_TRAP 1

/*
 * Boot options
 */
#define CONFIG_ZBOOT_ROM_TEXT 0x0
#define CONFIG_ZBOOT_ROM_BSS 0x0
#define CONFIG_CMDLINE "root=/dev/nfs nfsroot=192.168.18.204:/home/linuxnfsroot noinitrd init=linuxrc console=ttyS0 mem=40M ip=dhcp"
#undef CONFIG_XIP_KERNEL

/*
 * Floating point emulation
 */

/*
 * At least one emulation must be selected
 */
#define CONFIG_FPE_NWFPE 1
#define CONFIG_FPE_NWFPE_XP 1
#undef CONFIG_FPE_FASTFPE
#undef CONFIG_VFP

/*
 * Userspace binary formats
 */
#define CONFIG_BINFMT_ELF 1
#undef CONFIG_BINFMT_AOUT
#undef CONFIG_BINFMT_MISC
#undef CONFIG_ARTHUR

/*
 * Power management options
 */
#undef CONFIG_PM

/*
 * Device Drivers
 */

/*
 * Generic Driver Options
 */
#define CONFIG_STANDALONE 1
#define CONFIG_PREVENT_FIRMWARE_BUILD 1
#define CONFIG_FW_LOADER 1

/*
 * Memory Technology Devices (MTD)
 */
#define CONFIG_MTD 1
#undef CONFIG_MTD_DEBUG
#define CONFIG_MTD_CONCAT 1
#define CONFIG_MTD_PARTITIONS 1
#undef CONFIG_MTD_REDBOOT_PARTS
#define CONFIG_MTD_CMDLINE_PARTS 1
#undef CONFIG_MTD_AFS_PARTS

/*
 * User Modules And Translation Layers
 */
#define CONFIG_MTD_CHAR 1
#define CONFIG_MTD_BLOCK 1
#undef CONFIG_FTL
#undef CONFIG_NFTL
#undef CONFIG_INFTL

/*
 * RAM/ROM/Flash chip drivers
 */
#define CONFIG_MTD_CFI 1
#define CONFIG_MTD_JEDECPROBE 1
#define CONFIG_MTD_GEN_PROBE 1
#define CONFIG_MTD_CFI_ADV_OPTIONS 1
#define CONFIG_MTD_CFI_NOSWAP 1
#undef CONFIG_MTD_CFI_BE_BYTE_SWAP
#undef CONFIG_MTD_CFI_LE_BYTE_SWAP
#define CONFIG_MTD_CFI_GEOMETRY 1
#undef CONFIG_MTD_MAP_BANK_WIDTH_1
#define CONFIG_MTD_MAP_BANK_WIDTH_2 1
#undef CONFIG_MTD_MAP_BANK_WIDTH_4
#undef CONFIG_MTD_MAP_BANK_WIDTH_8
#undef CONFIG_MTD_MAP_BANK_WIDTH_16
#undef CONFIG_MTD_MAP_BANK_WIDTH_32
#define CONFIG_MTD_CFI_I1 1
#undef CONFIG_MTD_CFI_I2
#undef CONFIG_MTD_CFI_I4
#undef CONFIG_MTD_CFI_I8
#undef CONFIG_MTD_CFI_INTELEXT
#define CONFIG_MTD_CFI_AMDSTD 1
#define CONFIG_MTD_CFI_AMDSTD_RETRY 0
#undef CONFIG_MTD_CFI_STAA
#define CONFIG_MTD_CFI_UTIL 1
#undef CONFIG_MTD_RAM
#undef CONFIG_MTD_ROM
#undef CONFIG_MTD_ABSENT

/*
 * Mapping drivers for chip access
 */
#undef CONFIG_MTD_COMPLEX_MAPPINGS
#define CONFIG_MTD_PHYSMAP 1
#define CONFIG_MTD_PHYSMAP_START 0x38000000
#define CONFIG_MTD_PHYSMAP_LEN 0x2000000
#define CONFIG_MTD_PHYSMAP_BANKWIDTH 2
#undef CONFIG_MTD_ARM_INTEGRATOR
#undef CONFIG_MTD_EDB7312
#undef CONFIG_MTD_IMPA7

/*
 * Self-contained MTD device drivers
 */
#undef CONFIG_MTD_SLRAM
#undef CONFIG_MTD_PHRAM
#undef CONFIG_MTD_MTDRAM
#undef CONFIG_MTD_BLKMTD
#undef CONFIG_MTD_BLOCK2MTD

/*
 * Disk-On-Chip Device Drivers
 */
#undef CONFIG_MTD_DOC2000
#undef CONFIG_MTD_DOC2001
#undef CONFIG_MTD_DOC2001PLUS
#define CONFIG_MTD_SPIDEV 1

/*
 * NAND Flash Device Drivers
 */
#define CONFIG_MTD_NAND 1
#undef CONFIG_MTD_NAND_VERIFY_WRITE
#define CONFIG_MTD_NAND_IDS 1
#define CONFIG_MTD_NAND_ORION 1
#define CONFIG_MTD_NAND_ORION_SUPPORT 1
#undef CONFIG_MTD_NAND_ORION_NANDBOOT
#undef CONFIG_MTD_NAND_DISKONCHIP
#undef CONFIG_MTD_NAND_NANDSIM

/*
 * Parallel port support
 */
#undef CONFIG_PARPORT

/*
 * Plug and Play support
 */

/*
 * Block devices
 */
#undef CONFIG_BLK_DEV_COW_COMMON
#define CONFIG_BLK_DEV_LOOP 1
#undef CONFIG_BLK_DEV_CRYPTOLOOP
#undef CONFIG_BLK_DEV_NBD
#undef CONFIG_BLK_DEV_UB
#define CONFIG_BLK_DEV_RAM 1
#define CONFIG_BLK_DEV_RAM_COUNT 1
#define CONFIG_BLK_DEV_RAM_SIZE 16384
#define CONFIG_BLK_DEV_INITRD 1
#define CONFIG_INITRAMFS_SOURCE ""
#undef CONFIG_CDROM_PKTCDVD

/*
 * IO Schedulers
 */
#define CONFIG_IOSCHED_NOOP 1
#define CONFIG_IOSCHED_AS 1
#undef CONFIG_IOSCHED_DEADLINE
#undef CONFIG_IOSCHED_CFQ
#undef CONFIG_ATA_OVER_ETH

/*
 * ATA/ATAPI/MFM/RLL support
 */
#undef CONFIG_IDE

/*
 * SCSI device support
 */
#define CONFIG_SCSI 1
#define CONFIG_SCSI_PROC_FS 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD 1
#undef CONFIG_CHR_DEV_ST
#undef CONFIG_CHR_DEV_OSST
#undef CONFIG_BLK_DEV_SR
#define CONFIG_CHR_DEV_SG 1

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#define CONFIG_SCSI_MULTI_LUN 1
#undef CONFIG_SCSI_CONSTANTS
#undef CONFIG_SCSI_LOGGING

/*
 * SCSI Transport Attributes
 */
#undef CONFIG_SCSI_SPI_ATTRS
#undef CONFIG_SCSI_FC_ATTRS
#undef CONFIG_SCSI_ISCSI_ATTRS

/*
 * SCSI low-level drivers
 */
#undef CONFIG_SCSI_SATA
#undef CONFIG_SCSI_DEBUG

/*
 * PCMCIA SCSI adapter support
 */
#undef CONFIG_PCMCIA_AHA152X
#undef CONFIG_PCMCIA_FDOMAIN
#undef CONFIG_PCMCIA_NINJA_SCSI
#undef CONFIG_PCMCIA_QLOGIC
#undef CONFIG_PCMCIA_SYM53C500

/*
 * Multi-device support (RAID and LVM)
 */
#undef CONFIG_MD

/*
 * Fusion MPT device support
 */

/*
 * IEEE 1394 (FireWire) support
 */

/*
 * I2O device support
 */

/*
 * Networking support
 */
#define CONFIG_NET 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#define CONFIG_PACKET_MMAP 1
#define CONFIG_UNIX 1
#define CONFIG_NET_KEY 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#undef CONFIG_IP_ADVANCED_ROUTER
#undef CONFIG_IP_PNP
#undef CONFIG_NET_IPIP
#undef CONFIG_NET_IPGRE
#undef CONFIG_IP_MROUTE
#undef CONFIG_ARPD
#undef CONFIG_SYN_COOKIES
#undef CONFIG_INET_AH
#undef CONFIG_INET_ESP
#undef CONFIG_INET_IPCOMP
#undef CONFIG_INET_TUNNEL
#define CONFIG_IP_TCPDIAG 1
#undef CONFIG_IP_TCPDIAG_IPV6
#undef CONFIG_IPV6
#undef CONFIG_NETFILTER
#define CONFIG_XFRM 1
#undef CONFIG_XFRM_USER

/*
 * SCTP Configuration (EXPERIMENTAL)
 */
#undef CONFIG_IP_SCTP
#undef CONFIG_ATM
#undef CONFIG_BRIDGE
#undef CONFIG_VLAN_8021Q
#undef CONFIG_DECNET
#undef CONFIG_LLC2
#undef CONFIG_IPX
#undef CONFIG_ATALK
#undef CONFIG_X25
#undef CONFIG_LAPB
#undef CONFIG_NET_DIVERT
#undef CONFIG_ECONET
#undef CONFIG_WAN_ROUTER

/*
 * QoS and/or fair queueing
 */
#undef CONFIG_NET_SCHED
#undef CONFIG_NET_CLS_ROUTE

/*
 * Network testing
 */
#undef CONFIG_NET_PKTGEN
#undef CONFIG_NETPOLL
#undef CONFIG_NET_POLL_CONTROLLER
#undef CONFIG_HAMRADIO
#undef CONFIG_IRDA
#undef CONFIG_BT
#define CONFIG_NETDEVICES 1
#undef CONFIG_DUMMY
#undef CONFIG_BONDING
#undef CONFIG_EQUALIZER
#undef CONFIG_TUN

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#define CONFIG_MII 1
#undef CONFIG_SMC91X
#define CONFIG_CN100 1

/*
 * Ethernet (1000 Mbit)
 */

/*
 * Ethernet (10000 Mbit)
 */

/*
 * Token Ring devices
 */

/*
 * Wireless LAN (non-hamradio)
 */
#define CONFIG_NET_RADIO 1

/*
 * Obsolete Wireless cards support (pre-802.11)
 */
#undef CONFIG_STRIP
#undef CONFIG_PCMCIA_WAVELAN
#undef CONFIG_PCMCIA_NETWAVE

/*
 * Wireless 802.11 Frequency Hopping cards support
 */
#undef CONFIG_PCMCIA_RAYCS

/*
 * Wireless 802.11b ISA/PCI cards support
 */
#undef CONFIG_HERMES
#undef CONFIG_ATMEL

/*
 * Wireless 802.11b Pcmcia/Cardbus cards support
 */
#undef CONFIG_AIRO_CS
#undef CONFIG_PCMCIA_WL3501
#define CONFIG_NET_WIRELESS 1

/*
 * PCMCIA network device support
 */
#undef CONFIG_NET_PCMCIA

/*
 * Wan interfaces
 */
#undef CONFIG_WAN
#undef CONFIG_PPP
#undef CONFIG_SLIP
#undef CONFIG_SHAPER
#undef CONFIG_NETCONSOLE

/*
 * ISDN subsystem
 */
#undef CONFIG_ISDN

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#undef CONFIG_INPUT_MOUSEDEV
#undef CONFIG_INPUT_JOYDEV
#undef CONFIG_INPUT_TSDEV
#define CONFIG_INPUT_EVDEV 1
#undef CONFIG_INPUT_EVBUG

/*
 * Input Device Drivers
 */
#define CONFIG_INPUT_KEYBOARD 1
#undef CONFIG_KEYBOARD_ATKBD
#undef CONFIG_KEYBOARD_SUNKBD
#undef CONFIG_KEYBOARD_LKKBD
#undef CONFIG_KEYBOARD_XTKBD
#undef CONFIG_KEYBOARD_ORIONRC_1201
#undef CONFIG_KEYBOARD_NEWTON
#undef CONFIG_INPUT_MOUSE
#undef CONFIG_INPUT_JOYSTICK
#undef CONFIG_INPUT_TOUCHSCREEN
#undef CONFIG_INPUT_MISC

/*
 * Hardware I/O ports
 */
#undef CONFIG_SERIO
#undef CONFIG_GAMEPORT

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_HW_CONSOLE 1
#undef CONFIG_SERIAL_NONSTANDARD
#undef CONFIG_ORION_FPC
#define CONFIG_ORION_GPIO 1
#define CONFIG_ORION_GPIO2 1
#define CONFIG_ORION_SCI 1
#undef CONFIG_ORION_SCI_DEBUG
#undef CONFIG_CS_SERIAL_RC

/*
 * Serial drivers
 */
#define CONFIG_SERIAL_8250 1
#define CONFIG_SERIAL_8250_CONSOLE 1
#undef CONFIG_SERIAL_8250_CS
#define CONFIG_SERIAL_8250_NR_UARTS 2
#undef CONFIG_SERIAL_8250_EXTENDED
#define CONFIG_SERIAL_8250_ORION 1

/*
 * Non-8250 serial port support
 */
#define CONFIG_SERIAL_CORE 1
#define CONFIG_SERIAL_CORE_CONSOLE 1
#define CONFIG_UNIX98_PTYS 1
#undef CONFIG_LEGACY_PTYS

/*
 * IPMI
 */
#undef CONFIG_IPMI_HANDLER

/*
 * Watchdog Cards
 */
#define CONFIG_WATCHDOG 1
#undef CONFIG_WATCHDOG_NOWAYOUT

/*
 * Watchdog Device Drivers
 */
#undef CONFIG_SOFT_WATCHDOG
#define CONFIG_ORION_WDT 1

/*
 * USB-based Watchdog Cards
 */
#undef CONFIG_USBPCWATCHDOG
#undef CONFIG_NVRAM
#undef CONFIG_RTC
#undef CONFIG_DTLK
#undef CONFIG_R3964

/*
 * Ftape, the floppy tape device driver
 */
#undef CONFIG_DRM

/*
 * PCMCIA character devices
 */
#undef CONFIG_SYNCLINK_CS
#undef CONFIG_RAW_DRIVER

/*
 * TPM devices
 */

/*
 * Orion1.4 Xport devices
 */
#define CONFIG_XPORT_SUPPORT 1
#undef CONFIG_XPORT_BIG_DMABUFFER
#undef CONFIG_ORION_XPORT_DEBUG

/*
 * CSM1200/CSM1201 A/V devices
 */
#define CONFIG_VIDEO_SUPPORT 1

/*
 * Orion1.4 Audio devices
 */
#define CONFIG_AUDIO_SUPPORT 1

/*
 * Orion SPI devices
 */

/*
 * ORION I2C driver
 */
#define CONFIG_ORION_I2C 1
#define CONFIG_ORION_I2C_1201 1
#undef CONFIG_ORION_I2C_DEBUG
#undef CONFIG_ORION_I2C_FASTSPEED
#define CONFIG_ORION_I2C_EEPROM 1
#define CONFIG_ORION_I2C_EEPROM_CHIP_1_ADDR 0x50
#undef CONFIG_ORION_I2C_MULTI_EEPROMS
#define CONFIG_ORION_I2C_EEPROM_SUBADDR_LEN 2
#define CONFIG_ORION_I2C_EEPROM_PAGE_SIZE 32
#define CONFIG_ORION_I2C_EEPROM_SLEEP_TIME 5

/*
 * CSM1201 DF driver
 */
#define CONFIG_ORION_DF 1
#undef CONFIG_KERNEL_DF_DEBUG

/*
 * I2C support
 */
#define CONFIG_I2C 1
#undef CONFIG_I2C_CHARDEV

/*
 * I2C Algorithms
 */
#undef CONFIG_I2C_ALGOBIT
#undef CONFIG_I2C_ALGOPCF
#undef CONFIG_I2C_ALGOPCA

/*
 * I2C Hardware Bus support
 */
#undef CONFIG_I2C_ISA
#undef CONFIG_I2C_PARPORT_LIGHT
#undef CONFIG_I2C_STUB
#undef CONFIG_I2C_PCA_ISA

/*
 * Hardware Sensors Chip support
 */
#undef CONFIG_I2C_SENSOR
#undef CONFIG_SENSORS_ADM1021
#undef CONFIG_SENSORS_ADM1025
#undef CONFIG_SENSORS_ADM1026
#undef CONFIG_SENSORS_ADM1031
#undef CONFIG_SENSORS_ASB100
#undef CONFIG_SENSORS_DS1621
#undef CONFIG_SENSORS_FSCHER
#undef CONFIG_SENSORS_FSCPOS
#undef CONFIG_SENSORS_GL518SM
#undef CONFIG_SENSORS_GL520SM
#undef CONFIG_SENSORS_IT87
#undef CONFIG_SENSORS_LM63
#undef CONFIG_SENSORS_LM75
#undef CONFIG_SENSORS_LM77
#undef CONFIG_SENSORS_LM78
#undef CONFIG_SENSORS_LM80
#undef CONFIG_SENSORS_LM83
#undef CONFIG_SENSORS_LM85
#undef CONFIG_SENSORS_LM87
#undef CONFIG_SENSORS_LM90
#undef CONFIG_SENSORS_LM92
#undef CONFIG_SENSORS_MAX1619
#undef CONFIG_SENSORS_PC87360
#undef CONFIG_SENSORS_SMSC47B397
#undef CONFIG_SENSORS_SMSC47M1
#undef CONFIG_SENSORS_W83781D
#undef CONFIG_SENSORS_W83L785TS
#undef CONFIG_SENSORS_W83627HF

/*
 * Other I2C Chip support
 */
#undef CONFIG_SENSORS_DS1337
#undef CONFIG_SENSORS_EEPROM
#undef CONFIG_SENSORS_PCF8574
#undef CONFIG_SENSORS_PCF8591
#undef CONFIG_SENSORS_RTC8564
#undef CONFIG_I2C_DEBUG_CORE
#undef CONFIG_I2C_DEBUG_ALGO
#undef CONFIG_I2C_DEBUG_BUS
#undef CONFIG_I2C_DEBUG_CHIP

/*
 * Misc devices
 */

/*
 * Multimedia devices
 */
#undef CONFIG_VIDEO_DEV

/*
 * Digital Video Broadcasting Devices
 */
#undef CONFIG_DVB

/*
 * Graphics support
 */
#define CONFIG_FB 1
#define CONFIG_FB_CFB_FILLRECT 1
#define CONFIG_FB_CFB_COPYAREA 1
#define CONFIG_FB_CFB_IMAGEBLIT 1
#define CONFIG_FB_SOFT_CURSOR 1
#undef CONFIG_FB_MACMODES
#undef CONFIG_FB_MODE_HELPERS
#undef CONFIG_FB_TILEBLITTING
#undef CONFIG_FB_S1D13XXX
#define CONFIG_FB_ORION 1
#undef CONFIG_FB_ORION_BLIT
#undef CONFIG_FB_VIRTUAL

/*
 * Console display driver support
 */
#undef CONFIG_VGA_CONSOLE
#define CONFIG_DUMMY_CONSOLE 1
#undef CONFIG_FRAMEBUFFER_CONSOLE

/*
 * Logo configuration
 */
#undef CONFIG_LOGO
#undef CONFIG_BACKLIGHT_LCD_SUPPORT

/*
 * Sound
 */
#undef CONFIG_SOUND

/*
 * USB support
 */
#define CONFIG_USB_ARCH_HAS_HCD 1
#undef CONFIG_USB_ARCH_HAS_OHCI
#define CONFIG_USB 1
#undef CONFIG_USB_DEBUG

/*
 * Miscellaneous USB options
 */
#define CONFIG_USB_DEVICEFS 1
#undef CONFIG_USB_BANDWIDTH
#undef CONFIG_USB_DYNAMIC_MINORS
#undef CONFIG_USB_OTG

/*
 * USB Host Controller Drivers
 */
#undef CONFIG_USB_SL811_HCD

/*
 * USB Device Class drivers
 */
#undef CONFIG_USB_BLUETOOTH_TTY
#undef CONFIG_USB_ACM
#undef CONFIG_USB_PRINTER

/*
 * NOTE: USB_STORAGE enables SCSI, and 'SCSI disk support' may also be needed; see USB_STORAGE Help for more information
 */
#define CONFIG_USB_STORAGE 1
#undef CONFIG_USB_STORAGE_DEBUG
#undef CONFIG_USB_STORAGE_DATAFAB
#undef CONFIG_USB_STORAGE_FREECOM
#undef CONFIG_USB_STORAGE_DPCM
#undef CONFIG_USB_STORAGE_USBAT
#undef CONFIG_USB_STORAGE_SDDR09
#undef CONFIG_USB_STORAGE_SDDR55
#undef CONFIG_USB_STORAGE_JUMPSHOT

/*
 * USB Input Devices
 */
#define CONFIG_USB_HID 1
#define CONFIG_USB_HIDINPUT 1
#undef CONFIG_HID_FF
#undef CONFIG_USB_HIDDEV
#undef CONFIG_USB_AIPTEK
#undef CONFIG_USB_WACOM
#undef CONFIG_USB_KBTAB
#undef CONFIG_USB_POWERMATE
#undef CONFIG_USB_MTOUCH
#undef CONFIG_USB_EGALAX
#undef CONFIG_USB_XPAD
#undef CONFIG_USB_ATI_REMOTE

/*
 * USB Imaging devices
 */
#undef CONFIG_USB_MDC800
#undef CONFIG_USB_MICROTEK

/*
 * USB Multimedia devices
 */
#undef CONFIG_USB_DABUSB

/*
 * Video4Linux support is needed for USB Multimedia device support
 */

/*
 * USB Network Adapters
 */
#undef CONFIG_USB_CATC
#undef CONFIG_USB_KAWETH
#undef CONFIG_USB_PEGASUS
#undef CONFIG_USB_RTL8150
#undef CONFIG_USB_USBNET
#undef CONFIG_USB_ZD1201
#undef CONFIG_USB_MON

/*
 * USB port drivers
 */

/*
 * USB Serial Converter support
 */
#undef CONFIG_USB_SERIAL

/*
 * USB Miscellaneous drivers
 */
#undef CONFIG_USB_EMI62
#undef CONFIG_USB_EMI26
#undef CONFIG_USB_AUERSWALD
#undef CONFIG_USB_RIO500
#undef CONFIG_USB_LEGOTOWER
#undef CONFIG_USB_LCD
#undef CONFIG_USB_LED
#undef CONFIG_USB_CYTHERM
#undef CONFIG_USB_PHIDGETKIT
#undef CONFIG_USB_PHIDGETSERVO
#undef CONFIG_USB_IDMOUSE
#undef CONFIG_USB_TEST

/*
 * USB ATM/DSL drivers
 */

/*
 * USB Gadget Support
 */
#undef CONFIG_USB_GADGET
#define CONFIG_USB_INVENTRA_HCD 1
#define CONFIG_USB_INVENTRA_HCD_HOST 1
#define CONFIG_USB_INVENTRA_STATIC_CONFIG 1
#define CONFIG_USB_INVENTRA_DMA 1
#define CONFIG_USB_INVENTRA_HCD_LOGGING 0

/*
 * MMC/SD Card support
 */
#undef CONFIG_MMC

/*
 * File systems
 */
#define CONFIG_EXT2_FS 1
#define CONFIG_EXT2_FS_XATTR 1
#undef CONFIG_EXT2_FS_POSIX_ACL
#undef CONFIG_EXT2_FS_SECURITY
#define CONFIG_EXT3_FS 1
#define CONFIG_EXT3_FS_XATTR 1
#undef CONFIG_EXT3_FS_POSIX_ACL
#undef CONFIG_EXT3_FS_SECURITY
#define CONFIG_JBD 1
#undef CONFIG_JBD_DEBUG
#define CONFIG_FS_MBCACHE 1
#undef CONFIG_REISERFS_FS
#undef CONFIG_JFS_FS

/*
 * XFS support
 */
#undef CONFIG_XFS_FS
#undef CONFIG_MINIX_FS
#undef CONFIG_ROMFS_FS
#undef CONFIG_QUOTA
#undef CONFIG_DNOTIFY
#undef CONFIG_AUTOFS_FS
#undef CONFIG_AUTOFS4_FS

/*
 * CD-ROM/DVD Filesystems
 */
#define CONFIG_ISO9660_FS 1
#undef CONFIG_JOLIET
#undef CONFIG_ZISOFS
#define CONFIG_UDF_FS 1
#define CONFIG_UDF_NLS 1

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS 1
#define CONFIG_MSDOS_FS 1
#define CONFIG_VFAT_FS 1
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"
#define CONFIG_NTFS_FS 1
#undef CONFIG_NTFS_DEBUG
#undef CONFIG_NTFS_RW

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#define CONFIG_SYSFS 1
#define CONFIG_DEVFS_FS 1
#undef CONFIG_DEVFS_MOUNT
#undef CONFIG_DEVFS_DEBUG
#undef CONFIG_DEVPTS_FS_XATTR
#define CONFIG_TMPFS 1
#define CONFIG_TMPFS_XATTR 1
#undef CONFIG_TMPFS_SECURITY
#undef CONFIG_HUGETLB_PAGE
#define CONFIG_RAMFS 1

/*
 * Miscellaneous filesystems
 */
#undef CONFIG_ADFS_FS
#undef CONFIG_AFFS_FS
#undef CONFIG_HFS_FS
#undef CONFIG_HFSPLUS_FS
#undef CONFIG_BEFS_FS
#undef CONFIG_BFS_FS
#undef CONFIG_EFS_FS
#undef CONFIG_JFFS_FS
#define CONFIG_JFFS2_FS 1
#define CONFIG_JFFS2_FS_DEBUG 0
#define CONFIG_JFFS2_FS_NAND 1
#undef CONFIG_JFFS2_FS_NOR_ECC
#define CONFIG_JFFS2_COMPRESSION_OPTIONS 1
#define CONFIG_JFFS2_ZLIB 1
#define CONFIG_JFFS2_RTIME 1
#undef CONFIG_JFFS2_RUBIN
#undef CONFIG_JFFS2_CMODE_NONE
#define CONFIG_JFFS2_CMODE_PRIORITY 1
#undef CONFIG_JFFS2_CMODE_SIZE
#undef CONFIG_CRAMFS
#undef CONFIG_VXFS_FS
#undef CONFIG_HPFS_FS
#undef CONFIG_QNX4FS_FS
#undef CONFIG_SYSV_FS
#undef CONFIG_UFS_FS

/*
 * Network File Systems
 */
#define CONFIG_NFS_FS 1
#define CONFIG_NFS_V3 1
#undef CONFIG_NFS_V4
#undef CONFIG_NFS_DIRECTIO
#undef CONFIG_NFSD
#define CONFIG_LOCKD 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_SUNRPC 1
#undef CONFIG_RPCSEC_GSS_KRB5
#undef CONFIG_RPCSEC_GSS_SPKM3
#undef CONFIG_SMB_FS
#undef CONFIG_CIFS
#undef CONFIG_NCP_FS
#undef CONFIG_CODA_FS
#undef CONFIG_AFS_FS

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#undef CONFIG_ACORN_PARTITION
#undef CONFIG_OSF_PARTITION
#undef CONFIG_AMIGA_PARTITION
#undef CONFIG_ATARI_PARTITION
#undef CONFIG_MAC_PARTITION
#define CONFIG_MSDOS_PARTITION 1
#undef CONFIG_BSD_DISKLABEL
#undef CONFIG_MINIX_SUBPARTITION
#undef CONFIG_SOLARIS_X86_PARTITION
#undef CONFIG_UNIXWARE_DISKLABEL
#undef CONFIG_LDM_PARTITION
#undef CONFIG_SGI_PARTITION
#undef CONFIG_ULTRIX_PARTITION
#undef CONFIG_SUN_PARTITION
#undef CONFIG_EFI_PARTITION

/*
 * Native Language Support
 */
#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "iso8859-1"
#define CONFIG_NLS_CODEPAGE_437 1
#undef CONFIG_NLS_CODEPAGE_737
#undef CONFIG_NLS_CODEPAGE_775
#undef CONFIG_NLS_CODEPAGE_850
#undef CONFIG_NLS_CODEPAGE_852
#undef CONFIG_NLS_CODEPAGE_855
#undef CONFIG_NLS_CODEPAGE_857
#undef CONFIG_NLS_CODEPAGE_860
#undef CONFIG_NLS_CODEPAGE_861
#undef CONFIG_NLS_CODEPAGE_862
#undef CONFIG_NLS_CODEPAGE_863
#undef CONFIG_NLS_CODEPAGE_864
#undef CONFIG_NLS_CODEPAGE_865
#undef CONFIG_NLS_CODEPAGE_866
#undef CONFIG_NLS_CODEPAGE_869
#define CONFIG_NLS_CODEPAGE_936 1
#define CONFIG_NLS_CODEPAGE_950 1
#undef CONFIG_NLS_CODEPAGE_932
#undef CONFIG_NLS_CODEPAGE_949
#undef CONFIG_NLS_CODEPAGE_874
#undef CONFIG_NLS_ISO8859_8
#undef CONFIG_NLS_CODEPAGE_1250
#undef CONFIG_NLS_CODEPAGE_1251
#undef CONFIG_NLS_ASCII
#define CONFIG_NLS_ISO8859_1 1
#undef CONFIG_NLS_ISO8859_2
#undef CONFIG_NLS_ISO8859_3
#undef CONFIG_NLS_ISO8859_4
#undef CONFIG_NLS_ISO8859_5
#undef CONFIG_NLS_ISO8859_6
#undef CONFIG_NLS_ISO8859_7
#undef CONFIG_NLS_ISO8859_9
#undef CONFIG_NLS_ISO8859_13
#undef CONFIG_NLS_ISO8859_14
#undef CONFIG_NLS_ISO8859_15
#undef CONFIG_NLS_KOI8_R
#undef CONFIG_NLS_KOI8_U
#define CONFIG_NLS_UTF8 1

/*
 * Profiling support
 */
#undef CONFIG_PROFILING

/*
 * Kernel hacking
 */
#undef CONFIG_PRINTK_TIME
#undef CONFIG_DEBUG_KERNEL
#define CONFIG_LOG_BUF_SHIFT 14
#undef CONFIG_DEBUG_BUGVERBOSE
#define CONFIG_FRAME_POINTER 1
#undef CONFIG_DEBUG_USER

/*
 * Security options
 */
#undef CONFIG_KEYS
#undef CONFIG_SECURITY

/*
 * Cryptographic options
 */
#undef CONFIG_CRYPTO

/*
 * Hardware crypto devices
 */

/*
 * Library routines
 */
#define CONFIG_CRC_CCITT 1
#define CONFIG_CRC32 1
#define CONFIG_LIBCRC32C 1
#define CONFIG_ZLIB_INFLATE 1
#define CONFIG_ZLIB_DEFLATE 1
