obj-$(CONFIG_FB_ORION) += orionfb.o

ifdef CONFIG_ARCH_ORION_CSM1201
orionfb-objs := orionfb_dev.o orionfb_1201_hw.o
endif

ifdef  CONFIG_ARCH_ORION_CSM1200   
orionfb-objs := orionfb_dev.o orionfb_1200_hw.o
endif

